
name: Basic CI Workflow

on:
  push:
    branches: [ main ]


env:
  APP_NAME: my-first-app
  ENVIRONMENT: development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Display environment variables
        run: |
          echo "Application Name: $APP_NAME"
          echo "Environment: $ENVIRONMENT"

      - name: Run CI test
        run: |
          echo "GitHub Actions CI workflow is running"
          echo "Build completed successfully" 
