name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  APP_NAME: my-first-app
  ENVIRONMENT: development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print environment variables
        run: |
          echo "App: $APP_NAME"
          echo "Environment: $ENVIRONMENT"
          echo "Triggered by: ${{ github.event_name }}"

      - name: List repository files
        run: ls -la

      - name: Use a GitHub Secret
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          if [ -z "$MY_SECRET" ]; then
            echo "Secret is NOT set"
          else
            echo "Secret is set: $MY_SECRET"
          fi
          